### ISSUE TITLE
Support Gnome 43

### ISSUE THREAD

**Issue by MohammadMD1383** [mwahlroos/Nautiterm#4]
Thanks for your extension, but it doesn't work on gnome 43 - Ubuntu 22.10

**Comment by mwahlroos** [comment]
Thanks for the bug report. This is probably due to Gtk 4. I'll try and see if I can work out how to make the extension compatible with that, but it might take a while since I don't know how to do that right off the bat.

**Comment by MohammadMD1383** [comment]
Thanks for your effort:)

**Comment by mwahlroos** [comment]
I've added support for Gtk 4 in a separate [gtk4-support branch](https://github.com/mwahlroos/Nautiterm/tree/gtk4-support). It seems to work on Ubuntu 22.10.

It's currently mutually exclusive with supporting Gtk 3, and I haven't had time to see if it's possible to support both Gtk 3 and Gtk 4 based Nautilus extension APIs within the same extension.

Since the Gtk 3 based extension API is still being used in any older distribution releases as well as LTS ones, I'm keeping the default branch at Gtk 3 for now. I'm leaving this issue open until Gtk 4 support is in the default branch.

**Comment by MohammadMD1383** [comment]
Thanks for your effort.

I'll try it ASAP

**Comment by mwahlroos** [comment]
It's apparently easy to support both Nautilus API versions at the same time, so I'm also merging this to master.
